export const EnemyType = {
  GRUNT: 'grunt',
  FAST: 'fast',
  TANK: 'tank',
  HEALER: 'healer',
  BOSS: 'boss',
}

export const ENEMY_DEFS = {
  [EnemyType.GRUNT]: {
    name: 'Grunt',
    hp: 60,
    speed: 2.0,
    reward: 10,
    damage: 1,
    color: 0xCC4444,
    scale: 0.3,
    scoreValue: 5,
  },
  [EnemyType.FAST]: {
    name: 'Scout',
    hp: 30,
    speed: 4.0,
    reward: 8,
    damage: 1,
    color: 0x44CC44,
    scale: 0.22,
    scoreValue: 8,
  },
  [EnemyType.TANK]: {
    name: 'Brute',
    hp: 200,
    speed: 1.2,
    reward: 25,
    damage: 2,
    color: 0x666666,
    scale: 0.45,
    scoreValue: 15,
  },
  [EnemyType.HEALER]: {
    name: 'Shaman',
    hp: 80,
    speed: 1.8,
    reward: 15,
    damage: 1,
    color: 0x44CCCC,
    scale: 0.28,
    healRadius: 3,
    healAmount: 5,
    healRate: 2.0,
    scoreValue: 12,
  },
  [EnemyType.BOSS]: {
    name: 'Overlord',
    hp: 800,
    speed: 0.8,
    reward: 100,
    damage: 5,
    color: 0x880088,
    scale: 0.6,
    scoreValue: 50,
  },
}
